# Generated by Django 5.0.6 on 2024-09-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_questionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresult',
            name='is_blank',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='assigned_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
