# Generated by Django 5.0.6 on 2024-09-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questionresult_is_blank_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
