# Generated by Django 5.0.6 on 2024-09-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_delete_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_public',
        ),
    ]
