# Generated by Django 5.0.6 on 2024-09-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiz_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionresult',
            old_name='selected_answers',
            new_name='selected_answer_texts',
        ),
    ]
