# Generated by Django 5.0.6 on 2024-09-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_rename_selected_answers_questionresult_selected_answer_texts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionresult',
            old_name='selected_answer_texts',
            new_name='selected_answers',
        ),
    ]
